version: '3'

services:
  web:
    image: tsuglam/zendserver:2018.14beta
    ports:
      - 443
      - 10081
      - 1080
    environment:
      USERNAME: ${VOLUME_USERNAME}
      ZEND_LICENSE_KEY: N092A0108028319F0076562FECC40EF9
      ZEND_LICENSE_ORDER: 190913
      ZS_ADMIN_PASSWORD: qwerty
      VIRTUAL_HOST: web-${VOLUME_PROJECT}-${VOLUME_USERNAME}.${URL_DOMAIN}
      HTTPS_METHOD: redirect
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 443
    networks:
     - default
     - overshare
    volumes:
      - /dockerdata/${VOLUME_USERNAME}/${VOLUME_PROJECT}/${VOLUME_WEBDATA}/:/var/www/
    restart: always
    privileged: true
  redis:
    image: redis:3
    restart: always
    privileged: true
networks:
  overshare:
    external:
      name: overshare