version: '3'

services:
  web:
    image: thesiteup/docker-zendserver:9-php7.1
    ports:
      - ${PORT_HTTPS}:443
      - 10081
      - 1080
    environment:
      USERNAME: ${VOLUME_USERNAME}
      ZEND_LICENSE_KEY: CT92AG108028319F007671923E8ED9BA
      ZEND_LICENSE_ORDER: 190913
      ZS_ADMIN_PASSWORD: QAZwsx123GDL!!
      VIRTUAL_HOST: web-${VOLUME_PROJECT}-${VOLUME_USERNAME}.${URL_DOMAIN}
      LETSENCRYPT_HOST: web-${VOLUME_PROJECT}-${VOLUME_USERNAME}.${URL_DOMAIN}
      HTTPS_METHOD: redirect
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 443
    networks:
    - default
    - overshare
    volumes:
      - /dockerdata/${VOLUME_USERNAME}/${VOLUME_PROJECT}/${VOLUME_WEBDATA}/:/var/www
    restart: always
    privileged: true
  redis:
    image: redis:4
    restart: always
    privileged: true
networks:
  overshare:
    external:
      name: overshare